[package]
name = "day05"
version = "0.1.0"
authors = ["ingwinlu <winklerlukas+work@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
easybench = "1.0.0"

[profile.test]
opt-level = 3